### ISSUE TITLE
Something went wrong searching Hoogle!

### ISSUE THREAD

**Issue by Yurez23** [caneroj1/hoogle-vscode#10]
I have vscode v1.63.2, ghc v8.10.7, Haskell Language Server v1.5.1, hoogle-vscode v0.0.7. And any search results in an error "Something went wrong searching Hoogle!"

**Comment by Yurez23** [comment]
Looks like a Windows compatibility issue.
Error message from console:
[2022-01-21 13:14:29.383] [renderer1] [error] [Extension Host] Hoogle Error Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
